Al 123 implementation of routing
HRMS-AL/HRMS-Front pull request #106
Opened 2022-11-09 09:52 UTC by SnehaAlbiorix

2022-11-09 14:11 UTC, Parag-baldaniya commented on hrms-front/src/Pages/Dashboard/index.tsx
> +		<div>
It should be a proper formatted.

2022-11-09 14:11 UTC, Parag-baldaniya commented on hrms-front/src/Pages/Login/index.js
> +		<div>
It should be a proper formatted.

2022-11-10 07:33 UTC, SnehaAlbiorix commented on hrms-front/src/Pages/Dashboard/index.tsx
> +		<div>
formatted all files

2022-11-10 08:25 UTC, Parag-baldaniya approved these changes

2022-11-10 08:38 UTC, Jalpesh009 requested changes

2022-11-10 08:38 UTC, Jalpesh009 commented on hrms-front/package.json
> +    "prepare": "cd.. && husky install",
why  cd..?

2022-11-10 08:43 UTC, Parag-baldaniya commented on hrms-front/package.json
> +    "prepare": "cd.. && husky install",
I told her to add it. because without cd.. we do npm install husky gives error so once code pushed after that i'll check that issue.

2022-11-10 08:54 UTC, RenishIs commented on hrms-front/package.json
> +    "prepare": "cd.. && husky install",
See @SnehaAlbiorix @Parag-baldaniya @RiddhiAlbiorix  the another potential problem is  our folder structure of the frontend `hrms-front` it should not be there

 
![image](https://user-images.githubusercontent.com/89529118/201044774-5f1c8a72-97b9-4058-bedc-602534c207e3.png)

This should be in root folder
![image](https://user-images.githubusercontent.com/89529118/201044884-6780520e-bf0c-4738-84e8-6bfd7f546bcf.png)

2022-11-10 12:18 UTC, merged